### ISSUE TITLE
bug: cannot hide “video suggestions” sidebar anymore

### ISSUE THREAD

**Issue by val461** [inbasic/iyccenter#81]
It used to work. Now, the video suggestions remain displayed. Toggling the button changes nothing.
I use Firefox 61.0.2 (64-bit) on Arch Linux.

**Comment by Jasper-Dev** [comment]
i am experiencing the exact same problem on FireFox 62.0.3 (64-bits) windows 10

as a workaround i have installed a plug-in called stylus and added the code:
```css
.html5-endscreen,   /*the suggestion tiles after the video has ended*/
#related            /*the recommended videos sidebar*/
{
    display:none;
}

```
